main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('CV/', views.cv, name='cv'),
    path('mataKuliah/accepted/', views.accepted, name='accepted'),
    path('story1/', views.story1, name='story1'),
    path('mataKuliah/table', views.data_list, name='list'),
    path('mataKuliah/detail/<int:id>/', views.data_detail, name='data detail'),
    path('mataKuliah/delete/<int:id>/', views.data_delete, name='data delete'),
    path('form/', views.form, name='form')

]

story4ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story6/', include('story6.urls', namespace = "story6"))
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns= [
    path('peserta/register/<int:id>/', views.register, name='register'),
    path('acara/register/', views.tambahKegiatan, name = 'tambah-acara'),
    path('acara/', views.listKegiatan, name = "list-kegiatan" )
]

main/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class MataKuliah(models.Model):
    namaMatkul = models.CharField(max_length=100)
    dosenPengajar = models.CharField(max_length=100)
    sks = models.CharField(max_length=100)
    semester = models.CharField(max_length=100)
    kelas = models.CharField(max_length=100)
    deskripsi = models.TextField()

    def __str__(self):
        return self.namaMatkul

    def get_detail_url(self):
        return f"/mataKuliah/detail/{self.id}/"

    def get_delete_url(self):
        return f"/mataKuliah/delete/{self.id}/"

story6/models.py
from django.db import models

# Create your models here.


class Acara(models.Model):
    namaAcara = models.CharField(max_length=100)


class Peserta(models.Model):
    namaPeserta = models.CharField(max_length=100)
    acaraDiikuti = models.ForeignKey(
        Acara, default=None, on_delete=models.CASCADE)

main/forms.py
from django import forms
from .models import MataKuliah


class MatkulForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = [
            'namaMatkul',
            'dosenPengajar',
            'sks',
            'semester',
            'kelas',
            'deskripsi'
        ]

        widgets = {
            'namaMatkul': forms.TextInput(attrs={'class': 'form-control'}),
            'dosenPengajar': forms.TextInput(attrs={'class': 'form-control'}),
            'sks': forms.TextInput(attrs={'class': 'form-control'}),
            'semester': forms.TextInput(attrs={'class': 'form-control'}),
            'kelas': forms.TextInput(attrs={'class': 'form-control'}),
            'deskripsi': forms.Textarea(attrs={'class': 'form-control'}),
        }

story6/forms.py
from django import forms
from .models import Peserta, Acara


class AcaraForm(forms.ModelForm):
    class Meta:
        model = Acara
        fields = [
            'namaAcara',
        ]

        widgets = {
            'nama Acara': forms.TextInput(attrs={'class': 'form-control'})
        }


class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = [
            'namaPeserta',
        ]

        widgets = {
            'nama Peserta': forms.TextInput(attrs={'class': 'form-control'})
        }

main/views.py
from django.shortcuts import render, redirect
from .models import MataKuliah
from .forms import MatkulForm


def home(request):
    return render(request, 'main/home.html')


def cv(request):
    return render(request, 'main/cv.html')


def story1(request):
    return render(request, 'main/story1.html')


def accepted(request,):
    return render(request, 'main/accepted.html')


def form(request):
    formMatkul = MatkulForm(request.POST or None)
    if formMatkul.is_valid():
        formMatkul.save()
        return redirect('/mataKuliah/accepted/', )

    context = {
        'formMatkul': formMatkul
    }
    return render(request, 'main/form.html', context)


def data_list(request):
    obj = MataKuliah.objects.all()

    context = {
        'obj': obj
    }
    return render(request, "main/list.html", context)


def data_delete(request, id):
    obj = MataKuliah.objects.get(id=id)
    if request.method == "POST":
        obj.delete()
        return redirect('/mataKuliah/table')
    context = {
        'object': obj
    }
    return render(request, "main/delete.html", context)

def data_detail(request, id):
    obj = MataKuliah.objects.get(id=id)
    context = {
        'object' : obj
    }
    return render(request, 'main/detail.html', context)

story6/views.py
from django.shortcuts import render, redirect
from .models import Acara, Peserta
from .forms import AcaraForm, PesertaForm

# Create your views here.


def register(request, id):
    form = PesertaForm(request.POST or None)
    if(form.is_valid()):
        personInEvent = Peserta(acaraDiikuti=Acara.objects.get(
            id=id), namaPeserta=form.data['namaPeserta'])
        personInEvent.save()
        return redirect('/story6/acara')

    context = {
        'form': form
    }
    return render(request, "register.html", context)


def tambahKegiatan(request):
    form = AcaraForm(request.POST or None)
    if(form.is_valid()):
        form.save()
        return redirect('/story6/acara')

    context = {
        'form': form
    }
    return render(request, "newEvent.html", context)


def listKegiatan(request):
    person = Peserta.objects.all()
    acara = Acara.objects.all()
    if(request.method == 'POST'):
        Peserta.objects.get(id=request.POST['id']).delete()
        return redirect('/story6/acara')

    context = {
        'person': person,
        'acara': acara
    }
    return render(request, "list.html", context)

main/templates/main/accepted.html
{% extends 'base.html' %} {% load static %}

{% block meta %}
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
    rel="stylesheet"
  />

  <link rel="stylesheet" href="{% static 'css/index.css' %}" />

  <title>Story3 Putu</title>
{% endblock meta %}

{% block content%}
<div class="container-fluid delete-message">
    <form action="." method="POST">{% csrf_token %}
        <h1 class="display-4">Your data has been added to Database</h1>
        <a type="button" class="btn btn-primary btn-large" href="/mataKuliah/table">See Database</a>
    </form>
</div>

{% endblock content%}

main/templates/main/cv.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block meta %}
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
    rel="stylesheet"
  />
  <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  <title>Putu's CV</title>
  {% endblock meta %} {% block content %}
  <nav class="navbar navbar-expand-md fixed-top bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#intro"
        ><span class="oren">PW</span>igunarta</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarResponsive"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/story1">Story1</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="introcv" class="view">
    <div class="full-bg-img">
      <div class="carousel-caption">
        <h1 class="display-2 tebal"><span class="oren">Putu's</span> CV</h1>
        <h1 class="display-2 tebal">
          <span class="oren">Click</span> to Start
        </h1>
        <a type="button" class="btn btn-primary btn-large" href="#porto">
          See My CV
        </a>
      </div>
    </div>
  </div>

  <div class="CV1" id="porto"></div>

  <footer>
    <div class="container-fluid padding footer">
      <div class="col-lg-12 text-center">
        <h5 class="display-3 judulPutih">Keep in Touch!</h5>
        <h3 class="display-5 putih">
          <a href="mailto:pwigunarta@gmail.com" class="putih">Email </a>me for
          business Inquiries
        </h3>
      </div>
      <div class="row padding">
        <div class="col-12 social padding d-flex justify-content-center">
          <a
            href="https://www.facebook.com/pwigunarta"
            class="fa fa-facebook"
            target="_blank"
          ></a>
          <a
            href="https://www.instagram.com/putu.wig/"
            class="fa fa-instagram"
            target="_blank"
          ></a>
          <a
            href="https://www.linkedin.com/in/putu-wigunarta-16ba57192/"
            class="fa fa-linkedin"
            target="_blank"
          ></a>
        </div>
      </div>
    </div>
  </footer>
  {% endblock content %}
</html>

main/templates/main/delete.html
{% extends 'base.html' %} {% load static %}

{% block meta %}
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
    rel="stylesheet"
  />

  <link rel="stylesheet" href="{% static 'css/index.css' %}" />

  <title>Story3 Putu</title>
{% endblock meta %}

{% block content%}
<div class="container-fluid delete-message">
    <form action="." method="POST">{% csrf_token %}
        <h1 class="display-4">Are you sure want to delete "{{ object.namaMatkul }}" ?</h1>
        <p><input type="submit" value="Yes" class="btn btn-primary btn-large"></p>
        <a type="button" class="btn btn-primary btn-large" href="/mataKuliah/table">Cancel</a>
    </form>
</div>

{% endblock content%}

main/templates/main/detail.html
{% extends 'base.html' %}{% load static %}

{% block meta %}
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
    rel="stylesheet"
  />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="{% static 'css/index.css' %}" />

  <title>Story3 Putu</title>
{% endblock meta %}

{% block content%}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <div class="container-fluid">
  <a class="navbar-brand" href="/"
      ><span class="oren">PW</span>igunarta</a
  >
  <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarResponsive"
  >
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/form">Add Data</a>
    </li>
      </ul>
  </div>
  </div>
</nav>

<div class="container-fluid detail-data">
      {% if object %}
        <p class="judul">Nama Kegiatan</p>
        <p class="subjudul">{{object.namaMatkul}}</p><br>
        <p class="judul">Nama Dosen</p>
        <p class="subjudul">{{object.dosenPengajar}}</p><br>
        <p class="judul">Jumlah SKS</p>
        <p class="subjudul">{{object.sks}}</p><br>
        <p class="judul">Semester</p>
        <p class="subjudul">Semester {{object.semester}}</p><br>
        <p class="judul">Ruang Kelas</p>
        <p class="subjudul">kelas {{object.kelas}}</p><br>
        <p class="judul">Deskripsi Singkat</p>
        <p class="subjudul">{{object.deskripsi}}</p><br> 
        <a href='{{object.get_delete_url}}' class="btn btn-primary btn-large button-detail-data">Delete</a>
        <a href='/mataKuliah/table' class="btn btn-primary btn-large putih button-detail-data">Database</a>
    {% endif %}
</div>

{% endblock content%}

main/templates/main/form.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block meta %}
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
    rel="stylesheet"
  />
  <link rel="stylesheet" href="{% static 'css/index.css' %}" />

  <title>Story3 Putu</title>
  {% endblock meta %}
  
  {%block content %}
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <div class="container-fluid">
        <a class="navbar-brand" href="/"
            ><span class="oren">PW</span>igunarta</a
        >
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarResponsive"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/mataKuliah/table">Database</a>
            </li>
            </ul>
        </div>
        </div>
    </nav>

    <h1 class="judulForm judulOren d-flex justify-content-center">Form Mata Kuliah</h1>
    <div class="form">
      <div class="form-group">
        <form method="POST" > {% csrf_token %}
          {{ formMatkul.as_p}}
          <input type="submit" value="Save" class="btn btn-primary btn-large">
        </form>
      </div>
    </div>
  {% endblock content %}
</html>

main/templates/main/template.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

story6/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block meta%}
<link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
    rel="stylesheet"
  />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <title>Register Yourself</title>
{% endblock meta%}

{% block content%}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container-fluid">
    <a class="navbar-brand" href="/"
        ><span class="oren">PW</span>igunarta</a
    >
    <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarResponsive"
    >
        <span class="navbar-toggler-icon"></span>
    </button>
    </div>
</nav>

<div class="container-fluid table-responsive">
    <h1 class="judulOren d-flex justify-content-center padding judulForm">List Kegiatan</h1>
    <div class="row">
    {% for acara in acara %}
        <table class="table col-md-4">
            <thead class="thead-dark">
                <tr>
                <th scope="col">{{acara.namaAcara}}</th>
                <th scope="col"><a type="button" class="btn btn-primary btn-large" href="{% url 'story6:register' acara.id %}">Join</a> </th>
                </tr>
            </thead>
            <tbody>
                {% for person in person %}
                    {% if person.acaraDiikuti == acara %}
                        <tr>
                            <form action="" method="POST">{% csrf_token %}
                                <input value="{{person.id}}" type="hidden" name="id">
                                <td>{{person.namaPeserta}}</td>
                                <td><button type="submit" value="Submit" class="btn button-primary">Delete</td>
                            </form>                             
                        </tr>    
                    {%endif%}               
                {% endfor %}           
            </tbody>
        </table>
    {%endfor%}
    </div>  
    <a type="button" class="btn btn-primary btn-large" href="/story6/acara/register/">Add Event</a> 
</div>
{% endblock content%}

story6/templates/newEvent.html
{% extends 'base.html' %}
{% load static %}

{% block meta%}
<link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
    rel="stylesheet"
  />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>Register Yourself</title>
{% endblock meta %}

{% block content%}
<div class="container-fluid d-flex justify-content-center">
    <form action="" method="POST">
        {% csrf_token %}
        <h1>Masukkan Nama Acara yang Ingin Direncanakan</h1>
        {{ form.as_p}}
          <input type="submit" value="Save" class="btn btn-primary btn-large">
        
    </form>
</div>
{% endblock content%}